### ISSUE TITLE
结果为0

### ISSUE THREAD

**Issue by cold-eye** [Hzfinfdu/PLMTuningCompetition#2]
按照baseline跑完，也对比了提交示例。提交三次都是0分

**Comment by cold-eye** [comment]
[predictions.zip](https://github.com/Hzfinfdu/PLMTuningCompetition/files/9379419/predictions.zip)

**Comment by Hzfinfdu** [comment]
尝试直接打包六个文件夹，而不是将其放在一个文件夹predictions中打包

**Comment by cold-eye** [comment]
那么结果要提交六次，还是每个文件夹打包后，再打包成一个文件夹上传？

**Comment by Hzfinfdu** [comment]
选中六个文件夹打包，得到一个压缩文件

**Comment by Hzfinfdu** [comment]
例如zip -r predictions.zip AGNews SST-2 Yelp TREC MRPC SNLI

**Comment by cold-eye** [comment]
可以了，谢谢
