### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by W-ZN** [Hzfinfdu/PLMTuningCompetition#5]
在运行 `bbt.py` 时，通过更改 tensor 的类型（`.to(torch.int64)`），`bbt.py` 得以正常运行
而当训练完 `best.pt`，尝试运行 `test.py` 时（将 line 49  由 `for res, _, _ in test_api(` 为 `for res, _ in test_api(`，不然会报错），显示以下错误：
> RuntimeError: CUDA out of memory. Tried to allocate 818.00 MiB (GPU 0; 6.00 GiB total capacity; 4.33 GiB already allocated; 0 bytes free; 5.15 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

此时我并未运行其它进程

**Comment by Hzfinfdu** [comment]
test_api是更新过的，可以查看8.27中午微信群里的通知和readme，返回值由2个变成3个。可以更新一下。报错是因为显存满了，可以修改test api中的batch size参数，选择8或16可以解决这个问题

**Comment by W-ZN** [comment]
> test_api是更新过的，可以查看8.27中午微信群里的通知和readme，返回值由2个变成3个。可以更新一下。报错是因为显存满了，可以修改test api中的batch size参数，选择8或16可以解决这个问题

修改过 test_api 的参数后仍然提示报错
```
for res, _, _ in test_api(
        sentence_fn=sentence_fn,
        test_data_path=f'./test_datasets/{task_name}/encrypted.pth',
     embedding_and_attention_mask_fn=embedding_and_attention_mask_fn,
        hidden_states_and_attention_mask_fn=None,
        task_name=task_name,
        batch_size = 8,
        device=device
    ):
```
这是否是因为 win 环境下的 test_api 没有更新呢？

**Comment by Hzfinfdu** [comment]
是的，这周内会更新

**Comment by Hzfinfdu** [comment]
windows版本暂时是两个返回值，如果使用的是MLM，其他功能是相同的，不影响使用

**Comment by W-ZN** [comment]
您好，当我更新完win下的tesk_api，训练 `test.py` 时，python 提示：

>Some weights of RobertaForMaskedLM were not initialized from the model checkpoint at roberta-large and are newly initialized: ['lm_head.decoder.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

这是本人第一次参加NLP相关竞赛，因此可能问题可能比较低级，但还望能帮忙解答，非常感谢

**Comment by Hzfinfdu** [comment]
嗯嗯不要紧的，您可以随意提问，一起交流。这个提示是无所谓的，因为语言模型的lm head不是常规的线性层，其weight继承自embedding层的参数，训练时不会训练这个参数，您可以google一下关于这点的更多细节和原因。正因此，bias这个参数无法初始化，代码中会采用0初始化。这个提示不会影响表现
