### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by Hzfinfdu** [Hzfinfdu/PLMTuningCompetition#6]

**Comment by Hzfinfdu** [comment]
或许可以单独发你一个留出from_pretrained方法参数的test_api，可以让你从本地load from cache file，但是有些麻烦。之前跑过baseline吗？或者你们组的方法没有用到huggingface transformers
吗？

**Comment by hccngu** [comment]
目前只需要传出from_pretrained的pretrained_model_name_or_path参数即可，谢谢啦～

**Comment by Hzfinfdu** [comment]
[test_api_custom_model_path.cpython-38-x86_64-linux-gnu.so.zip](https://github.com/Hzfinfdu/PLMTuningCompetition/files/9484817/test_api_custom_model_path.cpython-38-x86_64-linux-gnu.so.zip)

**Comment by Hzfinfdu** [comment]
`def test_api(
        sentence_fn,
        test_data_path,
        embedding_and_attention_mask_fn=None,
        hidden_states_and_attention_mask_fn=None,
        task_name='SST-2',
        batch_size=32,
        device='cuda',
        tokenizer_path='roberta-large',
        model_path='roberta-large'
):`

**Comment by hccngu** [comment]
好的，感谢

**Comment by hccngu** [comment]
您好，改成新的文件后，
调包时已改为
from test_api_custom_model_path import test_api
from test_api_custom_model_path import RobertaEmbeddings
调用时代码为：
for res, _, _ in test_api(
        sentence_fn=sentence_fn,
        embedding_and_attention_mask_fn=embedding_and_attention_mask_fn,
        # embedding_and_attention_mask_fn=None,
        test_data_path=f'./test_datasets/{task_name}/encrypted.pth',
        task_name=task_name,
        device=device,
        tokenizer_path=args.model_name, 
        model_path=args.model_name,
    ):
但是会报错test_api() got an unexpected keyword argument 'tokenizer_path'，
可能是文件的问题，或者参数名有误？感谢您的回答

**Comment by Hzfinfdu** [comment]
给错文件了，sorry

**Comment by Hzfinfdu** [comment]
[test_api_custom_model_path.cpython-38-x86_64-linux-gnu.so.zip](https://github.com/Hzfinfdu/PLMTuningCompetition/files/9484856/test_api_custom_model_path.cpython-38-x86_64-linux-gnu.so.zip)

**Comment by hccngu** [comment]
![image](https://user-images.githubusercontent.com/55266130/188459981-1f149df2-dcdc-424b-a6af-99eae3412255.png)
新文件读包的时候就会报错诶？

**Comment by hccngu** [comment]
hello hello~~

**Comment by Hzfinfdu** [comment]
今天之内给您答复

**Comment by hccngu** [comment]
谢谢啦

**Comment by Hzfinfdu** [comment]
[test_api_custom_model_path.cpython-38-x86_64-linux-gnu.so.zip](https://github.com/Hzfinfdu/PLMTuningCompetition/files/9503189/test_api_custom_model_path.cpython-38-x86_64-linux-gnu.so.zip)
尝试fix了一下，如果有问题随时交流，前两天比较忙

**Comment by hccngu** [comment]
可以用了，非常感谢
