### ISSUE TITLE
可否对sentence_fn有更详细的说明？

### ISSUE THREAD

**Issue by oujieww** [Hzfinfdu/PLMTuningCompetition#8]
![image](https://user-images.githubusercontent.com/13203040/189465310-19140e54-c74b-4673-842a-0290cec586f6.png)
对这个函数具体是什么功能，在预测流程中什么位置，不是很明白，不知道咱们这里是否有更详细的说明？或者什么地方有相关参考资料？

**Comment by Hzfinfdu** [comment]
<img width="641" alt="image" src="https://user-images.githubusercontent.com/74953051/189467225-0dec1aec-9db3-496c-9a74-1571ba01bac9.png">
https://arxiv.org/pdf/2107.13586.pdf

**Comment by Hzfinfdu** [comment]
test.py更新过一版，这是prompt tuning中的template部分，用来对原句子做修饰，细节可以参照上图和论文

**Comment by oujieww** [comment]
好的，谢谢
